kind: ReplicaSet
apiVersion: v1
metadata:
  name: payment-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80

  tolerations:
  - key: "security"
    operator: "Equal"
    value: "high"
    effect: "NoSchedule"