apiVersion: v1
kind: Pod
metadata:
  name: redis-backend
  labels:
    app: redis-backend
spec:
  containers:
  - name: redis
    image: redis:latest
    ports:
    - containerPort: 6379
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-frontend
  template:
    metadata:
      labels:
        app: web-frontend
  affinity:
    affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - redis-backend
            topologyKey: kubernetes.io/hostname
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
  